Handle some corner cases
SFDO-Tooling/Snowfakery pull request #174
Opened 2020-11-11 20:09 UTC by prescod

A couple of corner cases which changed in recent versions.

Allow "none" as a return code from random_choice because sometimes NULL is a real choice.

Allow random_choice with a single item. It previously allowed this. Machine-generated Snowfakery files may sometimes generate a single-item random_choice.

2020-11-11 20:13 UTC, prescod commented
This function has 100% coverage despite coveralls being confused.

2020-11-11 20:13 UTC, davisagli approved these changes

2020-11-11 20:14 UTC, davisagli requested changes
Wait no, I'm not approving this on your holiday!

2020-11-12 14:24 UTC, davisagli approved these changes

2020-11-12 14:24 UTC, merged