Make CumulusCI Optional
SFDO-Tooling/Snowfakery pull request #404
Opened 2021-06-10 02:07 UTC by prescod

Make CumulusCI an optional requirement of Snowfakery. If you don't have it installed, some tests will be skipped.

2021-06-10 13:35 UTC, davisagli requested changes
Shouldn't this also include a change to .github/workflows/ci.yml to make sure that cumulusci is installed there?

2021-06-10 17:16 UTC, davisagli commented
What's up with the test failure?

2021-06-11 04:43 UTC, prescod commented
#405 fixes the test failures, @davisagli

2021-06-11 13:16 UTC, davisagli approved these changes

2021-06-11 19:14 UTC, merged