Allow fakers to build on previously populated fields.
SFDO-Tooling/Snowfakery pull request #420
Opened 2021-06-20 16:14 UTC by prescod

Allow fakers to build on previously populated fields, such as emails based on firstnames.

2021-08-02 21:39 UTC, boakley requested changes
We have a video call where we went over a few small changes. Let me know when you've done them and I'll make a final pass. Otherwise, this looks good to me.

2021-08-06 05:11 UTC, prescod commented on snowfakery/fakedata/fake_data_generator.py
> +    for first_name in ("{firstname}", "{firstname[0]}", "{firstname[0]}{firstname[1]}")
I'll pad firstname to be sure.

2021-08-06 05:18 UTC, prescod commented on snowfakery/fakedata/fake_data_generator.py
> +    def user_name(self, matching: bool = True):
i'll leave it undocumented until someone asks for the feature.

2021-08-06 05:18 UTC, prescod commented on snowfakery/fakedata/fake_data_generator.py
> +                year=str(random.randint(1955, 2020)),
i'll do that.

2021-08-09 14:39 UTC, boakley approved these changes
After having gone over the code with Paul, and seeing these last few changes, I'm satisfied.

2021-08-09 16:16 UTC, davisagli reviewed
Are any updates to documentation needed?

2021-08-16 17:33 UTC, prescod commented
@davisagli : I think I'd just consider this "making fake data more realistic" and not needing of docs unless it causes some confusion or problem for someone.

I'll also wait on documenting the new plugin local variables feature until someone asks for a "feature like local variables for plugins". Premature documentation locks me into a particular interface.

2021-08-16 17:33 UTC, merged