Document Jinja filters better
SFDO-Tooling/Snowfakery pull request #554
Opened 2021-12-01 00:54 UTC by prescod

Add a bit more documentation about Jinja filters.

2021-12-01 17:40 UTC, pconrad-sfdo requested changes

2021-12-01 17:40 UTC, pconrad-sfdo commented on docs/index.md
> +The relevant section of the Jinja document is called [Expressions](https://jinja.palletsprojects.com/en/2.11.x/templates/#expressions). It includes information about [Literals](https://jinja.palletsp
Should be:

> [Other Operators](https://jinja.palletsprojects.com/en/2.11.x/templates/#other-operators), [If Expressions](https://jinja.palletsprojects.com/en/2.11.x/templates/#if-expression), and [Python Methods](https://jinja.palletsprojects.com/en/2.11.x/templates/#python-methods).

2021-12-02 11:35 UTC, prescod commented on docs/index.md
> +The relevant section of the Jinja document is called [Expressions](https://jinja.palletsprojects.com/en/2.11.x/templates/#expressions). It includes information about [Literals](https://jinja.palletsp
```suggestion
The relevant section of the Jinja document is called [Expressions](https://jinja.palletsprojects.com/en/2.11.x/templates/#expressions). It includes information about [Literals](https://jinja.palletsprojects.com/en/2.11.x/templates/#literals), [Math](https://jinja.palletsprojects.com/en/2.11.x/templates/#math), [Comparisons](https://jinja.palletsprojects.com/en/2.11.x/templates/#comparisons), [Logic](https://jinja.palletsprojects.com/en/2.11.x/templates/#logic), [Other Operators](https://jinja.palletsprojects.com/en/2.11.x/templates/#other-operators), [If Expressions](https://jinja.palletsprojects.com/en/2.11.x/templates/#if-expression), [Python Methods] and (https://jinja.palletsprojects.com/en/2.11.x/templates/#python-methods).
```

2021-12-02 11:36 UTC, prescod commented on docs/index.md
> +The relevant section of the Jinja document is called [Expressions](https://jinja.palletsprojects.com/en/2.11.x/templates/#expressions). It includes information about [Literals](https://jinja.palletsp
@pconrad-sfdo This is fixed now.

2021-12-02 18:59 UTC, pconrad-sfdo approved these changes

2021-12-02 20:08 UTC, merged