Deep random_references and allow random_references to nicknames
SFDO-Tooling/Snowfakery pull request #639
Opened 2022-04-09 05:50 UTC by prescod

TBD

2022-05-23 06:48 UTC, mitchwd commented
Really appreciate your work here @prescod. This feature will make a huge difference for us at Lumary. 🙏 Thank you!

2022-05-31 19:03 UTC, jofsky requested changes

2022-05-31 20:38 UTC, jofsky submitted a review, later dismissed
Approving on condition that default random_references is set to list as discussed and follow up discussion!

2022-06-01 00:25 UTC, pconrad-sfdo commented on docs/index.md
> +The selected row can be any one that matches the object type (or nickname) and was already created in the current iteration of the recipe. For example, this previous recipe was executed twenty times
This whole section is confusing. I think what it's saying is it pulls a random row by object, but the object has to be created for it to exist (and get selected).  And if a recipe for 10 pets and owners gets executed 20 times, the pets that get assigned to owners created during the same iteration. But I'm not sure. However, the change that's being made (adding "(or nickname)" seems fine, so it doesn't make sense to block on this.

2022-06-01 00:41 UTC, pconrad-sfdo commented
**Here's a quick attempt to make the random_reference section a little clearer:**

The `random_reference property` creates a reference to a random, existing row from a table.

```
- object: Owner
  count: 10
  fields:
    name:
      fake: Name
- object: Pet
  count: 10
  fields:
    ownedBy:
      random_reference: Owner
```

To create a reference, `random_reference` looks for a row created in the current iteration of the recipe and matching the specified object type or nickname. In the above recipe, each `random_reference` specified in `ownedBy` will point to one of the ten `Owner` objects created in the same iteration. If you iterate over the recipe multiple times, in other words, each `Pet` object will be matched with one of the ten `Owner` objects created during the same iteration.

If `random_reference` finds no matches in the current iteration, it looks in previous iterations. This can happen, for example, when you try to create a reference to an object created with the `just_once` flag. Snowfakery cannot currently generate a random_reference to a future iteration of a recipe. 

Performance tip: Tables and nicknames that are referred to by `random_reference` are "indexed", which makes them slightly slower to generate than normal. This should seldom be a problem in practice, but if you experience performance problems you could switch to a normal reference to see if that improves things.

2022-06-03 21:30 UTC, jofsky approved these changes

2022-06-03 21:30 UTC, jofsky commented on docs/index.md
> +To create a reference, `random_reference` looks for a row created in the current iteration of the recipe and matching the specified object type or nickname. In the above recipe, each `random_referenc
```suggestion
To create a reference, `random_reference` looks for a row created in the current iteration of the recipe that matches the specified object type or nickname. In the above recipe, each `random_reference` specified in `ownedBy` will point to one of the ten `Owner` objects created in the same iteration. If you iterate over the recipe multiple times, in other words, each `Pet` object will be matched with one of the ten `Owner` objects created during the same iteration.
```

2022-06-03 22:06 UTC, merged