Throw plugin exceptions while line# is available
SFDO-Tooling/Snowfakery pull request #97
Opened 2020-08-08 01:23 UTC by prescod

Resolve plugins during the parsing process so that the line number and filename is available for error messages.

2020-09-15 02:04 UTC, prescod commented
@davisagli : Not an urgent fix but if you have a moment, we should close it out.

2020-09-15 14:27 UTC, davisagli requested changes

2020-09-15 14:27 UTC, davisagli commented on setup.py
> +exec(open("snowfakery/version.py").read())
This is not the same approach that we ended up with in https://github.com/SFDO-Tooling/Snowfakery/pull/102. Probably makes sense to merge that one first, then update this branch.

2020-09-21 20:33 UTC, davisagli approved these changes

2020-09-21 20:44 UTC, merged